apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: outer-orca-go 
  janus-idp.io/tekton: outer-orca-go
  backstage.io/kubernetes-id: outer-orca-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: outer-orca-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  